"""Stage79 2026 poll inputs: eligible polls per general seat, merged by source, aged to the data cutoff.

Reads the Stage82 live-inputs file (the run pinned by `seatPolls.electorateRun`, else the newest Stage82 run, read by `scripts.polling.electorate_live`, append-only), so a new electorate poll is a
data-only addition: the fitted inflation, half-life, cap and allowance stay fixed and nothing is regenerated by the poll alone.
Within a seat, polls of one source (the pollster after any sponsor prefix) within 14 days merge as in the frozen design; an older poll of a
source beyond that gap is superseded by the newer one. Different sources combine by inverse variance, each source's variance divided by the
square of its age factor relative to the freshest source, and the combined poll carries the freshest source's age (D123).
Fails closed: an unknown seat, a hash mismatch against the Stage82 index, or a bad share raises.
"""
import datetime
import re
import unicodedata
from . import model
from .common import read, fold, parameters, POLLS, DESIGN, PREFIX
from .data import derived
from scripts.polling import electorate_live

TARGET_FRAME = 'data/processed/forecast-readiness/snapshots/2026-10-05/target-frame.json'
FIT = PREFIX + '/fit.json'
SPONSORS = 'data/source-plans/seat-polls/sponsor-groups.json'


def source_key(pollster):
    """The pollster behind the fieldwork: the text after the last dash ("Taxpayers' Union - Curia" -> curia), lower case, letters and digits."""
    last = re.split(r'\s*[-\u2013\u2014]\s*', pollster)[-1]
    return re.sub(r'[^a-z0-9]+', '', unicodedata.normalize('NFKD', last).encode('ascii', 'ignore').decode().casefold())


def live_rows(run=None, sha256=None):
    """Stage79-form rows for the general-electorate polls of a Stage82 run: the pinned run `run` (date), else the newest. Seat names are
    matched to the target frame."""
    payload = {'polls': electorate_live.polls(run, sha256)}
    groups = read(SPONSORS)['groups']
    rows = []
    for poll in payload['polls']:
        if poll['type'] != 'general':
            continue
        key = source_key(poll['pollster'])
        group = next((g for g, members in groups.items() if key in members), 'all other groups')
        rows.append({'id': poll['id'], 'election': 2026, 'electorate': poll['seat'], 'pollster': poll['pollster'], 'sponsorGroup': group,
                     'fieldworkStart': poll['fieldwork']['start'], 'fieldworkEnd': poll['fieldwork']['end'], 'sampleSize': poll['sampleSize'],
                     'candidateVotePct': poll['electorateVotePct'], 'excluded': False,
                     'approximate': sorted(k for k, v in poll['electorateVoteFlags'].items() if v == 'approx'), 'evidenceGrade': poll['evidenceGrade']})
    return rows


def seat_ids():
    return {fold(r['canonicalName']): r['targetElectorateId'] for r in read(TARGET_FRAME)['records'] if r['scope'] == 'general'}


def canonical_names():
    return {r['canonicalName']: r['targetElectorateId'] for r in read(TARGET_FRAME)['records'] if r['scope'] == 'general'}


def date(text):
    return datetime.date.fromisoformat(text)


def inputs(as_of, fit=None, design=None, rows=None):
    """{seat id: {'value', 'variance', 'rho', 'ageWeeks', 'pollIds', ...}} for polls with fieldwork ending on or before `as_of`."""
    return combine(as_of, fit, design, rows)[0]


def combine(as_of, fit=None, design=None, rows=None):
    """(inputs, detail). `inputs` is as `inputs`. `detail` is {seat id: [poll record]} for every 2026 row of the seat: used polls carry
    `share` (fraction of the combined poll, summing to 1 over the seat's used polls, from the merge and inverse-variance weights) and
    unused ones a `reason`. Display evidence only: nothing in `inputs` depends on it."""
    design = design or read(DESIGN)
    fit = fit or read(FIT)
    p = parameters(design)
    ids = seat_ids()
    names = {i: n for n, i in canonical_names().items()}
    by_seat, detail, unused = {}, {}, {}
    for poll in (rows if rows is not None else live_rows()):
        if poll['election'] != 2026:
            continue
        if fold(poll['electorate']) not in ids:
            raise ValueError(f"unknown electorate in a seat poll: {poll['electorate']}")
        seat = ids[fold(poll['electorate'])]
        d = derived(poll, design)
        if poll['excluded']:
            reason = 'excluded from the model'
        elif not d['eligible']:
            reason = 'National and Labour are not the top two candidates, so the poll cannot update the National/Labour balance'
        elif date(poll['fieldworkEnd']) > date(as_of):
            reason = 'fieldwork ended after the data cutoff'
        else:
            reason = None
            allowance = design['pollError']['allowance'].get(poll['sponsorGroup'], design['pollError']['allowance']['all other groups'])
            variance = fit['inflation'] * d['samplingVariance'] + allowance ** 2
            by_seat.setdefault(seat, {}).setdefault(source_key(poll['pollster']), []).append({'poll': poll, 'value': d['value'], 'variance': variance})
        detail.setdefault(seat, {})[poll['id']] = {'pollId': poll['id'], 'pollster': poll['pollster'], 'sponsorGroup': poll['sponsorGroup'],
                                                   'fieldworkStart': poll['fieldworkStart'], 'fieldworkEnd': poll['fieldworkEnd'],
                                                   'sampleSize': poll['sampleSize'], 'sampleSizeAssumed': d['sampleSizeAssumed'],
                                                   'candidateVotePct': dict(poll['candidateVotePct']), 'approximate': poll.get('approximate', []),
                                                   'evidenceGrade': poll.get('evidenceGrade'), 'status': 'not-used' if reason else 'used',
                                                   'reason': reason, 'share': None}
    out = {}
    for seat, sources in by_seat.items():
        merged = []
        for entries in sources.values():
            entries.sort(key=lambda e: e['poll']['fieldworkEnd'])
            cluster = [entries[-1]]
            for earlier in reversed(entries[:-1]):  # an older poll beyond the merge gap is superseded by the newer one
                if (date(cluster[0]['poll']['fieldworkStart']) - date(earlier['poll']['fieldworkEnd'])).days > p['mergeDays']:
                    break
                cluster.insert(0, earlier)
            for e in entries:
                if e not in cluster:
                    detail[seat][e['poll']['id']].update(status='not-used', reason='superseded by a newer poll from the same pollster')
            value, variance = model.merge_same_source([(e['value'], e['variance']) for e in cluster], p['later'])
            end = max(date(e['poll']['fieldworkEnd']) for e in cluster)
            age = (date(as_of) - end).days / 7
            merged.append({'value': value, 'variance': variance, 'age': age, 'rho': model.age_factor(age, p['halfLifeWeeks']), 'cluster': cluster})
        freshest = max(merged, key=lambda m: m['rho'])
        weights = [(m['rho'] / freshest['rho']) ** 2 / m['variance'] for m in merged]  # relative age discount: variance / (rho / rho_freshest)^2
        precision = sum(weights)
        value = sum(w * m['value'] for w, m in zip(weights, merged)) / precision
        entries = sorted((e for m in merged for e in m['cluster']), key=lambda e: (e['poll']['fieldworkEnd'], e['poll']['id']))
        for w, m in zip(weights, merged):  # inside a source, the merge precisions (later polls at `later` times the variance)
            inner = [1 / (e['variance'] * (1 if i == 0 else p['later'])) for i, e in enumerate(m['cluster'])]
            for e, x in zip(m['cluster'], inner):
                detail[seat][e['poll']['id']]['share'] = (w / precision) * x / sum(inner)
        out[seat] = {'value': value, 'variance': 1 / precision, 'ageWeeks': freshest['age'], 'rho': freshest['rho'],
                     'cap': p['cap'], 'pollIds': [e['poll']['id'] for e in entries], 'electorate': names[seat],
                     'sources': len(merged)}
    order = lambda r: (r['fieldworkEnd'], r['pollId'])
    return out, {seat: sorted(polls.values(), key=order) for seat, polls in detail.items()}
