export const pages = [
  { path: '/', label: 'Forecast', title: 'A clearer view of the election.', description: 'A transparent framework for understanding national support, electorate contests and the shape of Parliament.', detail: 'National support estimates and probabilistic seat forecasts will appear here after the data and models have been validated.', needs: ['Validated polling inputs', 'Electorate models', 'Calibrated simulations'] },
  { path: '/electorates', label: 'Electorates', title: 'Every electorate. Explained.', description: 'Understand the local evidence behind each future electorate forecast.', detail: 'This section will connect boundary reconstruction, local party and candidate votes, split voting and candidate effects.', needs: ['Verified 2026 boundaries', 'Reconstructed 2023 results', 'Candidate evidence'] },
  { path: '/polls', label: 'Polls', title: 'The national picture.', description: 'An auditable view of polling evidence and its uncertainty.', detail: 'Polls and estimates have not been loaded. Future work will document fieldwork dates, pollster methods and modelling assumptions.', needs: ['Source register', 'Poll validation', 'Aggregation methodology'] },
  { path: '/mmp', label: 'MMP / Overhang', title: 'From votes to Parliament.', description: 'Explore how future simulations translate votes and electorate wins into seats.', detail: 'Qualification, Sainte-Laguë allocation, list MPs and overhangs are planned. No allocation engine or electoral rule assumptions are implemented.', needs: ['Verified electoral rules', 'Allocation tests', 'Simulation integration'] },
  { path: '/methodology', label: 'Methodology', title: 'Open assumptions. Visible uncertainty.', description: 'The methods should be as inspectable as the results.', detail: 'No statistical methods have been implemented. Future stages must distinguish overlapping effects, validate against held-out evidence and communicate limitations.', needs: ['Documented estimands', 'Validation design', 'Uncertainty reporting'] },
  { path: '/data', label: 'Data / Sources', title: 'Evidence with a paper trail.', description: 'Every future dataset must be traceable to its original resource.', detail: 'No election datasets have been collected. The repository defines source metadata, immutable raw storage and reproducible processing requirements.', needs: ['Exact source resource', 'Retrieval date and checksum', 'Reproducible processing script'] },
  { path: '/about', label: 'About', title: 'Built to be inspected.', description: 'An independent project modelling the 2026 New Zealand general election.', detail: 'This is a foundation-stage project, not an official election service. It currently provides architecture and documentation only. No forecast is available.', needs: ['Public methodology', 'Versioned evidence', 'Reproducible results'] },
] as const;
